#!/bin/bash 

BASE_URL="https://docs.nanocosmos.de/docs"

DEST_DIR=../website/build/docs/

build_searchindex()
{
    
    cd ./docs

    echo "creating searchindex"

    echo -n "[" >> tmp_idx

    # operate on source .md files
    find . -type f -name \*.md -print | while read fname
    do
        url=$(echo $fname | sed 's/^\.\(.*\)\.md$/\1/g') # strip file name dot and file extension

        # sanitize:
        ## drop lines with markup
        ## remove unwanted chars
        ## get titles and subtitles
        ## remove #s and add \n
        text=$(cat $fname \
                   | grep -ve "[</>]" \
                   | tr -d '"[]\r' \
                   | egrep "^#{1,2} .*$" \
                   | sed "s/^#\{1,2\} \(.*\)$/\1\n/g" )

        echo $text| while read w
        do
            # when not empty
            [[ -n $w ]] && \
            echo -n "{\"url\":\"$BASE_URL$url\",\"title\": \"$w\"}," >> tmp_idx
        done
    done
    # finalize and remove trailing ,
    echo -n "]" >> tmp_idx
    sed 's/,]/]/g' tmp_idx > searchindex.json

    mkdir -p $DEST_DIR

    cp searchindex.json $DEST_DIR

    echo "Created searchindex.json: $DEST_DIR/searchindex.json"

    rm tmp_idx 
    rm searchindex.json
}

build_searchindex $1 $2 $3 $4
